### PR TITLE
`docopt-ng`

### PR DESCRIPTION
**Pull request by casperdcl**
Required by https://github.com/SyneRBI/SIRF/pull/1415

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Unrelated error:
```
 /usr/lib/ccache/g++-9 -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -Wall -Werror -O3 -DNDEBUG  utilities/CMakeFiles/ismrmrd_test_xml.dir/ismrmrd_test_xml.cpp.o -o utilities/ismrmrd_test_xml  -Wl,-rpath,/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ISMRMRD/build:/usr/lib/x86_64-linux-gnu/hdf5/serial:/usr/share/miniconda/lib:  libismrmrd.so.1.15.0  /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so  /usr/share/miniconda/lib/libpugixml.so.1.15 && :
2026-07-21T18:40:10.6316111Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
2026-07-21T18:40:10.6317948Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
2026-07-21T18:40:10.6319902Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_4'
2026-07-21T18:40:10.6321488Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
2026-07-21T18:40:10.6323238Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
2026-07-21T18:40:10.6325051Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_slist_append@CURL_OPENSSL_4'
2026-07-21T18:40:10.6326594Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
2026-07-21T18:40:10.6328105Z /usr/bin/ld: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
```
No idea why this appears now. Seems ISMRMRD found the wrong hdf5

**Comment by KrisThielemans** [comment]
On the actual change, I don't know the difference between `docopt` and `docopt-ng`, so trust you.

**Comment by casperdcl** [comment]
it's a maintained fork (the original isn't really maintained) which fixes some bugs, vis. https://github.com/jazzband/docopt-ng

**Review by KrisThielemans — APPROVED** [review]

**Comment by KrisThielemans** [comment]
`-hdf5` native builds fail due to #1021. I'm fine to merge this nevertheless now (ideally with `[ci skip]` then, as it's going to fail anyway).
